#!/usr/bin/env ruby
require 'bundler/setup'
require 'json'
require 'pathname'
require 'open-uri'
require 'slack'
require 'optparse'

class SlackFileRemover
  attr_reader :slack_token, :backup_dir, :delete_after, :force_delete_after

  def initialize(slack_token:, backup_dir:, delete_after: nil, force_delete_after: nil)
    @slack_token = slack_token
    @backup_dir = Pathname(backup_dir)
    @delete_after = delete_after
    @force_delete_after = force_delete_after
  end

  def client
    @client ||= Slack.client(token: slack_token)
  end

  def run(dryrun: true)
    fetch_files.sort_by {|meta| meta['created'] }.each do |meta|
      age = (Time.now.to_f - meta['created']) / (60*60*24)  # in days

      to_delete = delete_after && delete_after > age && !meta['pinned_to']
      to_force_delete = force_delete_after && force_delete_after > age && !meta['pinned_to']
      to_backup = meta['is_public']

      if to_backup || to_delete
        actions = ((dryrun ? 'would ' : '') + [('backup' if to_backup), ('delete' if to_delete)].compact.join(' and ')).capitalize
        puts "#{actions} #{meta['id']} (#{age.to_i} days old)"

        unless dryrun
          if to_backup
            begin
              do_backup(meta)
            rescue
              warn "Error during backup: #{$!}"
              warn 'Removal skipped' if to_delete && !to_force_delete
              warn 'Delete anyway since it is too old' if to_force_delete
              next unless to_delete && to_force_delete
            end
          end

          if to_delete
            begin
             do_delete(meta)
            rescue
              warn "Error during removal: #{$!}"
            end
          end
        end
      end
    end
  end

  def fetch_files
    files = []
    loop.with_index(1) do |_, i|
      result = client.files_list(page: i)
      break if result['files'].empty?
      files.concat(result['files'])
    end
    files
  end

  def do_delete(meta)
    client.files_delete(file: meta['id'])
  end

  def do_backup(meta)
    metadir = (backup_dir + 'meta').tap(&:mkpath)
    datadir = (backup_dir + 'data').tap(&:mkpath)
    chandir = (backup_dir + 'channels').tap(&:mkpath)

    id = meta['id']
    extname = File.extname(meta['name'])

    metafile = metadir + (id + '.json')
    datafile = datadir + (id + extname)

    metafile.write(JSON.dump(meta))
    metafile.utime(Time.now, meta['created'])

    if !meta['is_external'] && meta['url_private_download']
      size =
        begin
          datafile.size
        rescue Errno::ENOENT
          nil
        end

      if size == meta['size']
        warn "Current backup for #{id} has the same size as the metadata. Download skipped"
      else
        open(meta['url_private_download'], 'Authorization' => "Bearer #{slack_token}") do |file|
          datafile.write(file.read)
          datafile.utime(Time.now, meta['created'])
        end

        if datafile.size != meta['size']
          fail 'Downloaded file has unexpected size'
        end
      end

      meta['channels'].each do |chan|
        link = (chandir + chan).tap(&:mkpath) + (id + extname)
        link.unlink rescue nil
        link.make_symlink('../../data/' + (id + extname))
      end
    end
  end
end

params = ARGV.getopts(
  '',  # no short options
  'backup-dir:',
  'dryrun',
  'delete-after:',
  'force-delete-after:'
)

fail "Set SLACK_TOKEN environment variable" unless ENV['SLACK_TOKEN']
fail "Specify --backup-dir=DIR" unless params['backup-dir']

SlackFileRemover.new(
  slack_token: ENV['SLACK_TOKEN'],
  backup_dir: params['backup-dir'],
  delete_after: params['delete_after'] && Float(params['delete_after']),
  force_delete_after: params['force_delete_after'] && Float(params['force_delete_after']),
).run(dryrun: params['dryrun'])
